name: Remote SSH CD

on:
  push:
    branches: [ master ]

jobs:
  ssh:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:

      - name: ls -al
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
          cd /var/www/adrianpardo.dev-react/
          ls -al